[api]
port = 54321
schemes = ["http", "https"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://localhost:3000"
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false

[auth.email.template]
[auth.email.template.confirmation]
content_path = ""

[analytics]
port = 54327
vector_port = 54328

[storage]
file_size_limit = "50MiB"
