[api]
port = 54321
schemes = ["http", "https"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
autoconfirm = false

[analytics]
port = 54327
vector_port = 54328

[storage]
file_size_limit = "50MiB"
